### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by mattboston** [admiralobvious/flask-simpleldap#18]
Is it possible to use Flask-SimpleLDAP not as an authentication mechanism, since I already have Flask-Login implemented, but for me to manage users/groups in Active Directory?  I would like to be able to connect to the Active Directory server, poll the list of users and groups, then update which groups a user is part of.  Also, it would be good if I could update the user's Active Directory password.

**Comment by admiralobvious** [comment]
Hello,

No, it is not possible. Flask-SimpleLDAP was really made to just be used for read-only operations hence the 'simple' in the name. Adding write operations would also create some major security concerns because if your web app has poor security, then anyone will have write access to your AD.

Nothing stops you from forking my code and adding those features yourself though. It should be relatively easy.
